Zeitpunkt: 2023-08-29 06:41:27,089
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 62, in run_analysis
    np_congruency.save_congruency_results()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/congruency/nominal_phrase_congruency.py", line 496, in save_congruency_results
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 06:42:03,211
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 62, in run_analysis
    np_congruency.save_congruency_results()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/congruency/nominal_phrase_congruency.py", line 496, in save_congruency_results
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 06:42:25,306
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 62, in run_analysis
    np_congruency.save_congruency_results()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/congruency/nominal_phrase_congruency.py", line 496, in save_congruency_results
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 06:44:15,886
Loggername: root
LogLevel: INFO
Nachricht: Ergebnisse wurden gespeichert
Modul: basic_logger
Funktion: log_info
Linie: 98
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 06:51:13,924
Loggername: root
LogLevel: INFO
Nachricht: Ergebnisse wurden gespeichert
Modul: basic_logger
Funktion: log_info
Linie: 98
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:06:09,605
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 44, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:06:13,138
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 44, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:07:32,253
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 44, in look_up_data_entry
    if merlin_corpus.get("conll"):
AttributeError: 'NoneType' object has no attribute 'get'

Nachricht: 'NoneType' object has no attribute 'get'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:08:28,896
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 45, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:08:38,363
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 45, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:08:50,155
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 45, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:09:55,491
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 46, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:12:18,018
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:12:21,073
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:13:00,035
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:13:23,982
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:13:23,982
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 42, in look_up_data_entry
    for entry in merlin_corpus:
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:13:51,139
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:14:18,155
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:26:41,080
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 90, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 21, in __get_ast_data
    file = open(
FileNotFoundError: [Errno 2] No such file or directory: ''

Nachricht: [Errno 2] No such file or directory: ''
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:26:45,483
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 90, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 21, in __get_ast_data
    file = open(
FileNotFoundError: [Errno 2] No such file or directory: ''

Nachricht: [Errno 2] No such file or directory: ''
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:27:09,725
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 91, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 21, in __get_ast_data
    file = open(
FileNotFoundError: [Errno 2] No such file or directory: 'GeneralPaths.TEST_NP_AST_FILE'

Nachricht: [Errno 2] No such file or directory: 'GeneralPaths.TEST_NP_AST_FILE'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:33:14,115
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 91, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 21, in __get_ast_data
    file = open(
OSError: [Errno 9] Bad file descriptor

Nachricht: [Errno 9] Bad file descriptor
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:44:41,938
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 52, in run_analysis
    morpho_results = demorphy.get_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 92, in get_raw_np_morphology
    np_data = self.get_read_in_np_file()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/demorphy_manager.py", line 83, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:45:02,358
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 95, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 104, in save_extracted_ast_nps
    with open(save_file, mode="w", encoding="utf-8", newline="") as save:
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/nps_user/outgoing/extracted_nominal_phrases/nps.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/nps_user/outgoing/extracted_nominal_phrases/nps.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:45:39,750
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 95, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 104, in save_extracted_ast_nps
    with open(save_file, mode="w", encoding="utf-8", newline="") as save:
FileNotFoundError: [Errno 2] No such file or directory: ' user/outgoing/extracted_nominal_phrases/nps.csv'

Nachricht: [Errno 2] No such file or directory: ' user/outgoing/extracted_nominal_phrases/nps.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:46:31,506
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 95, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 104, in save_extracted_ast_nps
    with open(save_file, mode="w", encoding="utf-8", newline="") as save:
FileNotFoundError: [Errno 2] No such file or directory: ' user/outgoing/extracted_nominal_phrases/nps.csv'

Nachricht: [Errno 2] No such file or directory: ' user/outgoing/extracted_nominal_phrases/nps.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:53:36,699
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 52, in run_analysis
    morpho_results = demorphy.get_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 92, in get_raw_np_morphology
    np_data = self.get_read_in_np_file()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/demorphy_manager.py", line 83, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:58:22,305
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 97, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 29, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:58:25,265
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 97, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 29, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:58:28,247
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 97, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 29, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:58:39,982
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 97, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 29, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 11:00:51,740
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 96, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 29, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 11:00:59,952
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 96, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 29, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 11:01:30,802
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 96, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 29, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 11:02:59,415
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 97, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 100, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 49, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 29, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 11:03:44,663
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 97, in extract_nps_from_ast_file
    np_file_handler.save_extracted_ast_nps()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 102, in save_extracted_ast_nps
    nps_dict = self.get_ast_data_overview()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 51, in get_ast_data_overview
    new_data = self.__get_ast_data()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/extractors/ast_nominal_phrase_extractor.py", line 31, in __get_ast_data
    new_data = ast.literal_eval(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    M. Meier,M. N Fem|_|Sg,Meier N Fem|_|Sg,M. Meier Müllergasse 1 12345 Stadt X Internationale Au-pair Vermittlung Bahnhofstr .
             ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Nachricht: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 14:32:08,024
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 55, in nominal_phrase_agreement_analysis
    morpho_results = demorphy.get_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 92, in get_raw_np_morphology
    np_data = self.get_read_in_np_file()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/demorphy_manager.py", line 83, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 14:32:12,110
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 55, in nominal_phrase_agreement_analysis
    morpho_results = demorphy.get_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 92, in get_raw_np_morphology
    np_data = self.get_read_in_np_file()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/demorphy_manager.py", line 83, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:09:24,893
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 82, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 323, in read_database
    cur.execute(self.sql_command)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:09:31,481
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 82, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 323, in read_database
    cur.execute(self.sql_command)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:09:34,002
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 82, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 323, in read_database
    cur.execute(self.sql_command)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:12:52,663
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 83, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 323, in read_database
    cur.execute(self.sql_command)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:12:56,907
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 83, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 323, in read_database
    cur.execute(self.sql_command)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:13:38,628
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 83, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 323, in read_database
    cur.execute(self.sql_command)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:14:12,040
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 83, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 323, in read_database
    cur.execute(self.sql_command,)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:15:30,582
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 83, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 323, in read_database
    cur.execute(self.sql_command)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:17:04,400
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 83, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 324, in read_database
    cur.execute(self.sql_command,)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:17:24,334
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 84, in extract_data_from_merlin_database
    for row in text_ids:
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:17:42,258
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 325, in read_database
    cur.execute(self.sql_command,)
TypeError: execute() argument 1 must be str, not tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 83, in extract_data_from_merlin_database
    text_ids = Merlin(sql_command=sql).read_database()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 328, in read_database
    catch_and_log_error(kill_if_fatal_error=True)
TypeError: catch_and_log_error() missing 2 required positional arguments: 'error' and 'custom_message'

Nachricht: catch_and_log_error() missing 2 required positional arguments: 'error' and 'custom_message'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:18:04,808
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 325, in read_database
    cur.execute(self.sql_command,)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:18:07,710
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 325, in read_database
    cur.execute(self.sql_command,)
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:18:57,801
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 325, in read_database
    cur.execute(self.sql_command,'French')
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:19:17,184
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 325, in read_database
    cur.execute(self.sql_command,('French'))
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:19:21,220
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 325, in read_database
    cur.execute(self.sql_command,('French',))
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:19:46,240
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 327, in read_database
    cur.execute(self.sql_command, ('French',))  # Example with a parameter
sqlite3.OperationalError: near "%": syntax error

Nachricht: near "%": syntax error
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:19:53,466
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 327, in read_database
    cur.execute(self.sql_command, ('French',))  # Example with a parameter
sqlite3.OperationalError: near "%": syntax error

Nachricht: near "%": syntax error
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:20:19,818
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 327, in read_database
    cur.execute(self.sql_command, ('French',))  # Example with a parameter
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:20:34,231
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 326, in read_database
    cur.execute(self.sql_command, ('French',))  # Example with a parameter
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:21:31,390
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 326, in read_database
    cur.execute(self.sql_command, ('French',))  # Example with a parameter
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:23:57,266
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 327, in read_database
    cur.execute(self.sql_command)  # Example with a parameter
TypeError: execute() argument 1 must be str, not tuple

Nachricht: execute() argument 1 must be str, not tuple
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:25:30,918
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 326, in read_database
    cur.execute(*sql_command)
TypeError: execute expected at most 2 arguments, got 70

Nachricht: execute expected at most 2 arguments, got 70
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 15:28:42,091
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 324, in read_database
    cur.execute(*self.sql_command)
sqlite3.OperationalError: near "general_mother_tongue": syntax error

Nachricht: near "general_mother_tongue": syntax error
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 16:46:56,206
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 54, in nominal_phrase_agreement_analysis
    morpho_results = demorphy.get_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 92, in get_raw_np_morphology
    np_data = self.get_read_in_np_file()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/demorphy_manager.py", line 83, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 16:47:51,377
Loggername: root
LogLevel: INFO
Nachricht: Ergebnisse wurden gespeichert
Modul: basic_logger
Funktion: log_info
Linie: 101
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 16:48:11,711
Loggername: root
LogLevel: INFO
Nachricht: Ergebnisse wurden gespeichert
Modul: basic_logger
Funktion: log_info
Linie: 101
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 16:50:30,344
Loggername: root
LogLevel: INFO
Nachricht: Ergebnisse wurden gespeichert
Modul: basic_logger
Funktion: log_info
Linie: 101
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 16:51:42,363
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 69, in nominal_phrase_agreement_analysis
    for row in np_congruency:
TypeError: 'NominalPhraseCongruency' object is not iterable

Nachricht: 'NominalPhraseCongruency' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 16:54:07,331
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 71, in nominal_phrase_agreement_analysis
    typer.echo(entry, congruency_check.get(entry))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
AttributeError: 'list' object has no attribute 'write'

Nachricht: 'list' object has no attribute 'write'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 16:54:32,971
Loggername: root
LogLevel: INFO
Nachricht: Ergebnisse wurden gespeichert
Modul: basic_logger
Funktion: log_info
Linie: 101
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 19:35:10,256
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 71, in nominal_phrase_agreement_analysis
    typer.echo(entry, congruency_check.get(entry))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
AttributeError: 'list' object has no attribute 'write'

Nachricht: 'list' object has no attribute 'write'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 19:42:25,042
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 71, in nominal_phrase_agreement_analysis
    typer.echo(1,congruency_check.get(entry))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
AttributeError: 'list' object has no attribute 'write'

Nachricht: 'list' object has no attribute 'write'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 19:49:22,018
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 77, in nominal_phrase_agreement_analysis
    status, np = congruency_check[:1]
TypeError: unhashable type: 'slice'

Nachricht: unhashable type: 'slice'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 19:50:02,853
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 77, in nominal_phrase_agreement_analysis
    status, np = congruency_check[0],congruency_check[1]
KeyError: 0

Nachricht: 0
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 19:55:43,143
Loggername: root
LogLevel: INFO
Nachricht: Die Ergebnisse der Auswertung wurden gespeichert
Modul: basic_logger
Funktion: catch_and_log_info
Linie: 101
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 19:58:15,667
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 47, in list_text_ids
    table.add_row(row)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich/table.py", line 460, in add_row
    raise errors.NotRenderableError(
rich.errors.NotRenderableError: unable to render tuple; a string or other renderable object is required

Nachricht: unable to render tuple; a string or other renderable object is required
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 20:00:54,788
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 324, in read_database
    cur.execute(*self.sql_command)
sqlite3.OperationalError: no such column: general_mother_language

Nachricht: no such column: general_mother_language
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 20:02:27,751
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 324, in read_database
    cur.execute(*self.sql_command)
sqlite3.OperationalError: no such column: text_len_in_char

Nachricht: no such column: text_len_in_char
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 20:19:21,707
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 72, in get_show_text_by_id
    typer.echo(entry, entries_extracted_by_text_id.get(entry))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
AttributeError: 'str' object has no attribute 'write'

Nachricht: 'str' object has no attribute 'write'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 20:26:19,203
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Ein Problem ist innerhalb der Hauptanwendung aufgetreten. Bitte die Protokolldatei für weitere Informationen überprüfen. 
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/main.py", line 79, in <module>
    main_typer_app()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 232, in get_command
    click_command = get_group(typer_instance)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 218, in get_group
    group = get_group_from_info(TyperInfo(typer_instance))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 360, in get_group_from_info
    sub_group = get_group_from_info(sub_group_info)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 356, in get_group_from_info
    command = get_command_from_info(command_info=command_info)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 432, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 413, in get_params_convertors_ctx_param_name_from_function
    click_param, convertor = get_click_param(param)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 720, in get_click_param
    TyperOption(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/core.py", line 268, in __init__
    super().__init__(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 2495, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 2072, in __init__
    self.name, self.opts, self.secondary_opts = self._parse_decls(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 2609, in _parse_decls
    raise TypeError(f"Name '{name}' defined twice")
TypeError: Name 'data_source' defined twice

Nachricht: Name 'data_source' defined twice
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

